Survey/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Survey.Models;
using Survey.Services;
using Survey.ViewModels;

namespace Survey.Controllers
{
    public class SurveyController : Controller
    {
        private ISurveyService _surveyService;

        public SurveyController()
        {
        }

        public SurveyController(ISurveyService surveyService = null)
        {
            _surveyService = surveyService ?? new SurveyService();
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            _surveyService = new SurveyService();
        }

        // GET: Survey
        public ActionResult View(int id = 1)
        {
            var survey = _surveyService.GetSurvey(id);
            return View(survey);
        }

        [HttpPost]
        public ActionResult SubmitSurvey(SurveyAnswer submission)
        {
            //if (form.HasKeys() && form["Id"] != null && int.TryParse(form["Id"], out surveyId))
            //{
            //    var submission = new Submission
            //    {
            //        SurveyId = surveyId,
            //        Completed = DateTime.UtcNow,
            //        SubmissionAnswers = new List<SubmissionAnswer>()
            //    };

            //    foreach (var key in form.AllKeys)
            //    {
            //        int questionId;
            //        var question = key.Split('.');
            //        if (question.Length != 3 || question[0] != "Question" || !int.TryParse(question[2], out questionId))
            //            continue;

            //        int answerId;
            //        switch (question[1])
            //        {
            //            case "Single":
            //                if (!int.TryParse(form[key], out answerId))
            //                    continue;

            //                submission.SubmissionAnswers.Add( new SubmissionAnswer
            //                {
            //                    QuestionId = questionId,
            //                    AnswerId = answerId
            //                });

            //                break;
            //            case "Multiple":
            //                var answers = form[key].Split(',');
            //                foreach (var answer in answers)
            //                {
            //                    if (!int.TryParse(answer, out answerId))
            //                        continue;

            //                    submission.SubmissionAnswers.Add(new SubmissionAnswer
            //                    {
            //                        QuestionId = questionId,
            //                        AnswerId = answerId
            //                    });
            //                }
            //                break;
            //            case "Rating":
            //            case "Text":
            //                submission.SubmissionAnswers.Add(new SubmissionAnswer
            //                {
            //                    QuestionId = questionId,
            //                    AnswerText = form[key]
            //                });
            //                break;
            //        }
            //    }

            //    if (submission.SubmissionAnswers.Any())
            //        _surveyService.CreateSubmission(submission);
            //}
            return View("ThankYou");
        }

        [Authorize]
        public ActionResult Dashboard(int id = 1)
        {
            var submissions = _surveyService.GetSurveySubmissions(id).ToList();

            if (submissions.Any())
            {
                ViewBag.SurveyName = _surveyService.GetSurveyTitle(submissions.First().SurveyId);

                ViewBag.TotalSubmissions = submissions.Count();

                var ratings = submissions.SelectMany(x => x.SubmissionAnswers).Where(x => x.Question.Type == QuestionType.Rating).ToList();
                ViewBag.Ratings = ratings.Sum(x => float.Parse(x.AnswerText))/ratings.Count();

                var questions = submissions.SelectMany(x => x.SubmissionAnswers).GroupBy(x=>x.QuestionId).OrderByDescending(x => x.Count());
                ViewBag.MostAnswered = _surveyService.GetQuestionText(questions.First().Key);
            }
            else
            {
                ViewBag.SurveyName = "No submissions found";
            }
            

            return View(submissions);
        }
    }
}

Survey/Views/SurveyB/Dashboard.cshtml
@using Survey.Models
@model IEnumerable<Submission>

@{
    ViewBag.Title = "Dashboard";
}

<div class="jumbotron">
    <h2>Dashboard</h2>
</div>
<div class="row">
    <div class="col-lg-6">
        <h3>Submissions</h3>
        <div><h4>@ViewBag.SurveyName</h4></div>
        <div class="bs-example">
            <div class="panel-group" id="accordion">
                @{ var index = 0; } 
                @foreach (var submission in Model)
                {
                    var lastQuestion = -1;
                    index++;
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse_@index">@submission.Completed</a>
                            </h4>
                        </div>
                        <div id="collapse_@index" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>
                                    @foreach (var answer in submission.SubmissionAnswers)
                                    {
                                        if (lastQuestion != answer.QuestionId)
                                        {
                                            <li>@answer.Question.Text</li>
                                        }

                                        if (answer.Question.Type == QuestionType.Multiple || answer.Question.Type == QuestionType.Single)
                                        {
                                            <span>@answer.Answer.Text. </span>
                                        }
                                        else
                                        {
                                            <span>@answer.AnswerText</span>
                                        }
                                        lastQuestion = @answer.QuestionId;
                                    }
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <h3>Stats</h3>
        <h4>Total submissions:</h4>@ViewBag.TotalSubmissions
        <h4>Overall ratings:</h4>@ViewBag.Ratings
        <h4>Most answered question:</h4>@ViewBag.MostAnswered
    </div>
</div>

Survey/Views/SurveyB/View.cshtml
@using Survey.Models
@model Survey
@{
    ViewBag.Title = "Home Page";
}

<div class="content">
    <div class="row lead header">
        <h2>@Model.Header</h2>
    </div>
    @{
        using (Html.BeginForm("SubmitSurvey", "Survey", FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Id)
            foreach (var question in Model.Questions.OrderBy(x => x.Order))
            {
                <div class="row question">
                    @switch (question.Type)
                    {
                        case QuestionType.Text:
                            Html.RenderPartial("_QuestionTextPartial", question);
                            break;
                        case QuestionType.Multiple:
                            Html.RenderPartial("_QuestionMultiplePartial", question);
                            break;
                        case QuestionType.Single:
                            Html.RenderPartial("_QuestionSinglePartial", question);
                            break;
                        case QuestionType.Rating:
                            Html.RenderPartial("_QuestionRatingPartial", question);
                            break;
                    }
                </div>
            }
            <button type="submit" class="btn-lg">Done</button>
        }
    }
</div>

Survey/Views/SurveyB/_QuestionMultiplePartial.cshtml
@model Survey.Models.Question

<div class="question-text">
    @Model.Text
</div>
<div>
    @foreach (var answer in Model.Answers)
    {
        <input type="checkbox" name="Question.@Model.Type.@Model.Id" value="@answer.Id"/>
        <label for="@answer.Id">@answer.Text</label>
        <br/>
    }
</div>

Survey/Views/SurveyB/_QuestionRatingPartial.cshtml
@model Survey.Models.Question

<div class="question-text">
    @Model.Text
</div>
<div class="row">
    <div class="col-sm-10">
        Not at all likely
    </div>
    <div class="col-sm-2">
        Extremely likely
    </div>
</div>
<div class="row">
    @for (var i = 0; i <= 10; i++)
    {
        <div class="col-sm-1"> <input type="radio" name="Question.@Model.Type.@Model.Id" value="@i"/> @i </div>
    }
</div>

Survey/Views/SurveyB/_QuestionSinglePartial.cshtml
@model Survey.Models.Question

<div class="question-text">
    @Model.Text
</div>
<div>
    @foreach (var answer in Model.Answers)
    {
        <input type="radio" name="Question.@Model.Type.@Model.Id" value="@answer.Id" />
        <label for="@answer.Id">@answer.Text</label>
        <br />
    }
</div>

Survey/Views/SurveyB/_QuestionTextPartial.cshtml
@model Survey.Models.Question

<div class="question-text">
    @Model.Text
</div>
<div>
    <textarea name="Question.@Model.Type.@Model.Id"></textarea>
</div>